version: "3"
services:
  product-service:
    build: .
    container_name: product-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-products:5432/testdb
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db-products
  db-products:
    image: postgres
    container_name: db-products
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin-products:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - db-products
volumes:
  pgdata: